# Site settings
author: Ryland c. Grounds
title: Merging with the Meowtrix, a journey of ascension 
header-img: img/home-bg.png
email: rylandgrounds@gmail.com
copyright_name: Ryland c. Grounds
description: > # this means to ignore newlines until "baseurl:"
  I'm a variable, and my scope is life
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  VonLos

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
